--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/snarerectify/BetterBrag
build-by-default: true
branches:
- main
projects:
  BetterBrag:
    path: ""
    libs:
      - src: Paroxity/Commando/Commando
        version: ^3.0.0
      - src: muqsit/InvMenu/InvMenu
        version: ^4.6.5
        branch: "pm5"
...
