name: BetterBrag
author: snare
api: 5.3.0
version: 1.0.0
main: snare\BetterBrag\BetterBrag

permissions:
  betterbrag.brag.command:
    default: true
  betterbrag.command.start:
    default: true
  betterbrag.command.stop:
    default: true
  betterbrag.command.view:
    default: true
  betterbrag.command.list:
    default: true
